name: Run RSpec tests

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  run-rspec-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: [3.3]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - name: Run tests
        run: bundle exec rspec
